name: NetDevOps Core CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Local Repository Source Code
      uses: actions/checkout@v4

    - name: Initialize Production Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Network Automation Linters & Dependencies
      run: |
        python -m pip upgrade pip
        pip install flake8 yamllint

    - name: Execute Code Linting (Python Code Integrity Check)
      run: |
        # Stop the pipeline execution if there are any syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Execute Structured Configuration Data Validation (YAML Lint)
      run: |
        # Verifies that your Ansible Playbooks or Router Variables match strict formatting parameters
        yamllint .
